# Generated by Django 2.2.6 on 2020-06-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_letter_for_room_rooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter_for_room',
            options={'ordering': ['-date'], 'verbose_name': 'Сообщение для комнаты', 'verbose_name_plural': 'Сообщения для комнат'},
        ),
        migrations.AddField(
            model_name='letter_for_room',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.Rooms', verbose_name='Комната'),
        ),
    ]
